docs/guide/README.md
Update Guide documentation with Typescript module alias setup with ts-node.
Also update the generator template with this feature could be awesome!
Thank you!
(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))
If so, please mention them to keep the conversations linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.
If your changes involve …
=> Update Guide with Typescript module alias setup

lib/service-specs-to-mongoose.js, package-lock.json, test/helpers/movie.schema-default.js, test/service-specs-to-mongoose.test.js
Adding code for default property support mongoose schema generation.
=> Added default property  support for mongoose

lib/specs.js
Reverts feathers-plus/generator-feathers-plus#88
=> Revert "Allow tests to run from Mac private folder"

generators/writing/templates/README.md.ejs
(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))
Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.
If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).
Thanks for contributing to Feathers! :heart:
=> Remove semi-colon typo in 'endpoint'

generators/writing/templates/src/services/name/name.class.ejs
=> fix imports of App interface from services in subfolders

generators/writing/index.js, generators/writing/templates/_configs/index.js, generators/writing/templates/_configs/nodemon.json.js, generators/writing/templates/_configs/package.json.js, package.json
The generator does not provide a development environment for generated typescript applications. This request provides this environment using nodemon, with automated linting and reloading.
No current issues
This request relates to pull request feathers-plus#83, providing the development environment portion of the original request. The linting environment fix from request feathers-plus#83, along with updates to generator tests, are provided in separate pull requests
Though there are no issues currently open for this pull request, there are two anticipated issues with the current implementation:
1. When using the dev:seed script, the database is reseeded on every reload.
2. When live updates result in errors, continued reloads may result in a memory leak. This may be an issue with how …
=> Typescript development environment

generators/writing/templates/src/services/graphql/sql.execute.knex.ejs
#122 
I'm not able to get the tests running, possibly because I'm on windows. Could somone test it for me? I'll try to on my linux machine if not
=> correctly import Knex

test-expands/a-gens/ts/test-authentication.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/a-gens/ts/test-hook-integ.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/a-gens/ts/test-hook-unit.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/a-gens/ts/test-service.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-1-generic.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-1-memory.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-1-mongo.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-1-mongoose.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-1-nedb.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-2-hooks.test-expected/src1/services/graphql/sql.execute.knex.ts, test-expands/ts-cumulative-2-sequelize-services.test-expected/src1/services/graphql/sql.execute.knex.ts
tests for #126 (correctly import Knex)
=> Tests for #126

generators/writing/templates/tsconfig.json
Reverts feathers-plus/generator-feathers-plus#138
=> Revert "Fixed tsconfig.json"

docs/get-started/README.md
updated docs/get-started/readme.md and adjusted the location of the secret from package.json to config/default.json.  I mean I wouldn't put the secret in package.json ¯\_(ツ)_/¯
=> updated docs/get-started/readme.md

docs/get-started/README.md
=> Docs updated for generated index field.

generators/writing/templates/src/app.ejs, test-expands/a-specs/service-sequelize-mssql.test-expected/src1/app.js
Fix for https://github.com/feathers-plus/generator-feathers-plus/issues/174
=> Fix syntax error for mssql. Issue#174

generators/writing/templates/src/_adapters/sequelize.ejs
=> Clean typescript sequelize update

test-expands/cumulative-2-sequelize-services.test-expected/src1/sequelize.js, test-expands/ts-cumulative-2-sequelize-services.test-expected/src1/sequelize.ts
See #169, #171, and #182 for context
=> Clean typescript sequelize update tests

generators/codelist/index.js, lib/code-fragments.js, lib/specs.js
- Pass spec to fragment refresh
- Parse custom resources found in spec and add to code fragments
- Codelist formatting logic moved from codelist generator to code-fragments.js via formatCodelist, flattenCodelist, and flattenCodelistModule utils
=> Updates to allow custom resources in codelist

generators/codelist/index.js, generators/writing/index.js, lib/specs.js
=> Updated codelist output pull with custom resources

generators/codelist/index-prototype.js, lib/code-fragments-prototype.js, package-lock.json, package.json
Stash prototype code we'll need after we revert https://github.com/feathers-plus/generator-feathers-plus/pull/186 and https://github.com/feathers-plus/generator-feathers-plus/pull/187
=> Codelist revert 1

generators/codelist/index.js, generators/writing/index.js, lib/specs.js
Reverts feathers-plus/generator-feathers-plus#187
=> Revert "Updated codelist output pull with custom resources"

generators/codelist/index.js, lib/code-fragments.js, lib/specs.js
Reverts feathers-plus/generator-feathers-plus#186
=> Revert "Updates to allow custom resources in codelist"

package-lock.json, package.json
Refactor generators/writing/index.js into separate modules per command.
=> Refactor 0

generators/writing/app.js, generators/writing/index.js, generators/writing/service.js, lib/service-specs-to-typescript.js
=> Refactor 2

generators/writing/app.js, package.json
Make same changes as in https://github.com/feathers-plus/generator-feathers-plus/pull/200/commits/3eaae25665ea2b23f5d2f6956f3b48c21f3b1f1f
=> Winston repo now inclu7des TS typings.

generators/writing/authentication.js, generators/writing/graphql.js, generators/writing/service.js, package-lock.json, package.json
No longer mutate context object in generators/writing/* modules
=> Refactor 12

package-lock.json, package.json
Resolves https://github.com/feathers-plus/generator-feathers-plus/issues/220
=> Do not regenerate channels.?s

generators/writing/app.js
Resolves https://github.com/feathers-plus/generator-feathers-plus/issues/220
=> Do not REgenerate channels.js.

generators/writing/templates/src/_adapters/sequelize-mssql.ejs
(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))
Generated TS code has missing parenthesis and an extra curly brace in sequelize-mssql.ts
#224 
If so, please mention them to keep the conversations linked together.
My first PR, be gentle.
=> Mal Formed TS Code Issue 224

generators/writing/templates/src/services/_service/name.service-mongodb.ejs
This is a baby step towards fixing https://github.com/feathers-plus/generator-feathers-plus/issues/230
It exposes the promise in a variable so we can use the magic comments to work around the bug in that issue.
=> Expose mongodb promise as variable

lib/service-specs-to-mongoose.js, test/helpers/users.schema-enum.js, test/service-specs-to-mongoose.test.js
Currently, when you export a service, some attributes in JSON-Schema are not exported into Mongoose Schema, ex: ref, minLength... 
This PR :
* Allow additionnal attributes (like minLength, min, ref)
* Format date is exported as Date type
* Array are exported as array of type or array of subschema
Source JSON Schema :
```js
// Fields in the model.
properties: {
// !code: schema_properties
id:        { type: 'ID' },
parentId:  { type: 'ID', ref: 'User' },
friendIds: {
type: 'array',
items: { type: 'ID', ref: 'User' },
default: []
},
tags: { type: 'array', items: { type: 'string'} },
email:     { minLength: 8, maxLength: 40, faker: 'internet.email' },
firstName: { minLength: 2, maxLength: 15, faker: 'name.firstName' },
lastName:  { minLength: 2, maxLength: 30, faker: 'name.lastName' }, …
```
=> Improve json schema export to mongoose

generators/writing/app.js, generators/writing/templates/_configs/package.json.js, package-lock.json, package.json, test-expands/a-gens/ts/test-authentication.test-expected/package.json, test-expands/a-gens/ts/test-hook-integ.test-expected/package.json, test-expands/a-gens/ts/test-hook-unit.test-expected/package.json, test-expands/a-gens/ts/test-service.test-expected/package.json, test-expands/ts-cumulative-1-generic.test-expected/package.json, test-expands/ts-cumulative-1-memory.test-expected/package.json, test-expands/ts-cumulative-1-mongo.test-expected/package.json, test-expands/ts-cumulative-1-mongoose.test-expected/package.json, test-expands/ts-cumulative-1-nedb.test-expected/package.json, test-expands/ts-cumulative-2-hooks.test-expected/package.json, test-expands/ts-cumulative-2-sequelize-services.test-expected/package.json, test-expands/ts-name-space.test-expected/package.json
Resolves issue https://github.com/feathers-plus/generator-feathers-plus/issues/242
=> Start seed ts

lib/service-specs-to-mongoose.js
=> Mongoose schema shouldn’t modify Feathers schema

generators/writing/index.js, lib/service-specs-to-mongoose.js, package-lock.json, package.json
A fix for https://github.com/feathers-plus/generator-feathers-plus/pull/251
=> Fix pr 246
